[project]
name = "dcs-lso"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "constantly>=23.10.4",
    "fastapi>=0.142.2",
    "httpx>=0.28.1",
    "piper-tts>=1.8.0",
    "pyacmi>=1.2.4",
    "python-multipart>=0.0.32",
    "sqlalchemy>=2.1.1",
    "uvicorn>=0.54.0",
]

[project.scripts]
dcs-lso = "dcs_lso.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/dcs_lso"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
